mod management_access;

use axum::{
    middleware,
    routing::{any, get, patch, post, put},
    Router,
};

#[cfg(test)]
pub(crate) use self::management_access::{
    is_management_path, management_route_specs, ManagementRouteSpec,
};
use self::management_access::{management_role_gate, unregistered_management_route};

use crate::{management, proxy, state::AppState};

pub(crate) fn router_without_test_peer_default(state: AppState) -> Router {
    Router::new()
        .route("/health", get(|| async { "ok" }))
        .route("/ready", get(management::readiness))
        .route("/management/pools", get(management::list_pools))
        .route("/management/channels", get(management::list_channels))
        .route(
            "/management/client-tokens",
            get(management::list_client_tokens).post(management::create_client_token),
        )
        .route(
            "/management/client-tokens/:id",
            patch(management::update_client_token_scope),
        )
        .route(
            "/management/client-tokens/:id/disable",
            post(management::disable_client_token),
        )
        .route(
            "/management/client-tokens/:id/enable",
            post(management::enable_client_token),
        )
        .route("/management/providers", get(management::providers))
        .route(
            "/management/registry/providers/:id",
            put(management::upsert_registry_provider),
        )
        .route(
            "/management/registry/providers/:id/disable",
            post(management::disable_registry_provider),
        )
        .route(
            "/management/registry/providers/:id/enable",
            post(management::enable_registry_provider),
        )
        .route("/management/accounts", get(management::accounts))
        .route(
            "/management/registry/accounts/:id",
            put(management::upsert_registry_account),
        )
        .route(
            "/management/registry/accounts/:id/disable",
            post(management::disable_registry_account),
        )
        .route(
            "/management/registry/accounts/:id/enable",
            post(management::enable_registry_account),
        )
        .route(
            "/management/registry/channels/:id",
            put(management::upsert_registry_channel),
        )
        .route(
            "/management/registry/channels/:id/disable",
            post(management::disable_registry_channel),
        )
        .route(
            "/management/registry/channels/:id/enable",
            post(management::enable_registry_channel),
        )
        .route(
            "/management/credential-sets",
            get(management::credential_sets),
        )
        .route(
            "/management/credential-sets/:id/operations",
            get(management::credential_set_operations),
        )
        .route(
            "/management/credential-sets/:id/credentials",
            get(management::list_credential_set_credentials),
        )
        .route(
            "/management/credential-sets/:id/imports",
            get(management::credential_set_imports),
        )
        .route(
            "/management/credential-sets/:id/imports/:batch_id",
            get(management::credential_set_import),
        )
        .route(
            "/management/credential-sets/:id/credentials/:credential_id",
            get(management::credential_set_credential),
        )
        .route(
            "/management/credential-sets/:id/credentials/:credential_id/metadata",
            put(management::set_credential_set_credential_metadata),
        )
        .route(
            "/management/credential-sets/:id/credentials/:credential_id/history",
            get(management::credential_set_credential_history),
        )
        .route(
            "/management/credential-sets/:id/credentials/:credential_id/probe",
            post(management::probe_credential_set_credential),
        )
        .route(
            "/management/credential-sets/:id/credentials/:credential_id/probes",
            get(management::credential_set_credential_probes),
        )
        .route(
            "/management/credential-sets/:id/credentials/:credential_id/apply-latest-probe/plan",
            get(management::credential_probe_apply_plan),
        )
        .route(
            "/management/credential-sets/:id/credentials/:credential_id/apply-latest-probe",
            post(management::apply_latest_credential_probe),
        )
        .route(
            "/management/credential-sets/:id/credentials/import",
            post(management::import_credential_set_credentials),
        )
        .route(
            "/management/credential-sets/:id/credentials/:credential_id/expire",
            post(management::expire_credential_set_credential),
        )
        .route(
            "/management/credential-sets/:id/credentials/:credential_id/restore",
            post(management::restore_credential_set_credential),
        )
        .route(
            "/management/credential-sets/:id/credentials/:credential_id/quota-exhaust",
            post(management::quota_exhaust_credential_set_credential),
        )
        .route(
            "/management/credential-sets/:id/credentials/:credential_id/disable",
            post(management::disable_credential_set_credential),
        )
        .route(
            "/management/credential-sets/:id/credentials/:credential_id/enable",
            post(management::enable_credential_set_credential),
        )
        .route(
            "/management/credential-sets/:id/credentials/:credential_id/reset-cooldown",
            post(management::reset_credential_set_credential_cooldown),
        )
        .route("/management/model-routes", get(management::model_routes))
        .route(
            "/management/model-availability",
            get(management::model_availability),
        )
        .route(
            "/management/registry/model-routes/*model",
            put(management::upsert_registry_model_route),
        )
        .route(
            "/management/model-discovery/sync-plan",
            post(management::model_discovery_sync_plan),
        )
        .route(
            "/management/model-discovery/sync-apply",
            post(management::model_discovery_sync_apply),
        )
        .route(
            "/management/policy-profiles",
            get(management::policy_profiles),
        )
        .route(
            "/management/registry/policy-profiles/:id",
            put(management::upsert_registry_policy_profile),
        )
        .route(
            "/management/policy-profiles/:id",
            get(management::policy_profile),
        )
        .route(
            "/management/routing-profiles",
            get(management::routing_profiles),
        )
        .route(
            "/management/registry/routing-profiles/:id",
            put(management::upsert_registry_routing_profile),
        )
        .route(
            "/management/routing-profiles/:id",
            get(management::routing_profile),
        )
        .route(
            "/management/routing/preview",
            get(management::routing_preview),
        )
        .route("/management/runtime", get(management::runtime))
        .route(
            "/management/explain/runtime",
            get(management::explain_runtime),
        )
        .route(
            "/management/runtime/reload-diff",
            get(management::runtime_reload_diff),
        )
        .route(
            "/management/health/serving",
            get(management::serving_health),
        )
        .route(
            "/management/health/resilience",
            get(management::resilience_health),
        )
        .route(
            "/management/runtime/reload",
            post(management::reload_runtime),
        )
        .route("/management/alerts", get(management::alerts))
        .route("/management/channels/:id", get(management::get_channel))
        .route(
            "/management/channels/:id/model-discovery",
            post(management::discover_channel_models),
        )
        .route(
            "/management/channels/:id/reset-health",
            post(management::reset_channel_health),
        )
        .route(
            "/management/channels/:id/disable",
            post(management::disable_channel),
        )
        .route(
            "/management/channels/:id/enable",
            post(management::enable_channel),
        )
        .route(
            "/management/channels/:id/error-rules",
            get(management::error_rules),
        )
        .route(
            "/management/channels/:id/credentials",
            get(management::list_channel_credentials),
        )
        .route(
            "/management/channels/:id/credentials/:credential_id/expire",
            post(management::expire_channel_credential),
        )
        .route(
            "/management/channels/:id/credentials/:credential_id/restore",
            post(management::restore_channel_credential),
        )
        .route(
            "/management/channels/:id/credentials/:credential_id/quota-exhaust",
            post(management::quota_exhaust_channel_credential),
        )
        .route(
            "/management/channels/:id/credentials/:credential_id/disable",
            post(management::disable_channel_credential),
        )
        .route(
            "/management/channels/:id/credentials/:credential_id/enable",
            post(management::enable_channel_credential),
        )
        .route(
            "/management/channels/:id/credentials/:credential_id/reset-cooldown",
            post(management::reset_channel_credential_cooldown),
        )
        .route("/management/events", get(management::list_events))
        .route(
            "/management/response-filter-events",
            get(management::response_filter_events),
        )
        .route(
            "/management/routing-telemetry",
            get(management::routing_telemetry),
        )
        .route("/management", any(unregistered_management_route))
        .route("/management/*path", any(unregistered_management_route))
        .route("/v1/*path", any(proxy::proxy_openai_compatible))
        .route("/pools/:pool/*path", any(proxy::proxy_named_pool))
        .route_layer(middleware::from_fn_with_state(
            state.clone(),
            management_role_gate,
        ))
        .with_state(state)
}
